app.py
from flask import Flask
from views import views

app = Flask(__name__)
app.register_blueprint(views) 

if __name__ == "__main__":
    app.run(debug=True, port=8000)

views.py
from flask import render_template, Blueprint, request

views = Blueprint("views", __name__)

@views.route("/")
def home():
    return render_template("index.html")

@views.route("/contact")
def contact():
    return render_template("contact.html")

@views.route("/about")
def about():
    return render_template("about.html")

@views.route("/products")
def products():
    return render_template("products.html")

@views.route("/care")
def care():
    return render_template("care.html")

@views.route("/cart")
def cart():
    return render_template("cart.html")

@views.route("/redcorn")
def redcorn():
    return render_template("redcorn.html")

@views.route("/yellowgecko")
def yellowgecko():
    return render_template("yellowgecko.html")

@views.route("/beardeddragon")
def beardeddragon():
    return render_template("beardeddragon.html")

@views.route("/ballpython")
def ballpython():
    return render_template("ballpython.html")

@views.route("/crestedgecko")
def crestedgecko():
    return render_template("crestedgecko.html")

@views.route("/chameleon")
def chameleon():
    return render_template("chameleon.html")

templates/about.html
{% extends 'base.html' %}

{% block content %}
<body>
<div class="about">
    <h3>About Us</h3>
        <img src="{{url_for('static', filename='images/petshop.jpg')}}" alt="image of store" height=30% width=40% float=left/>
    <p>Exoticteptilestore was produced in view of the petted darling. We see pets as individuals from the family, so our point is to give clients items and administrations that can guarantee their darling pet will appreciate an upbeat, solid life. We know how essential the human-creature bond is, so our promise to quality creature care reaches out to each aspect of our business.</p>
    <p> Have you at any point met an enthusiastic creature sweetheart? An obstinate, fringe-fixated pet proprietor? All things considered, permit us the joy of acquainting you with our client benefit office. Every one of our clients bolsters staff individuals who have more than 10 years of involvement in their related pet field.</p>
    <p>Have an inquiry? We have the appropriate response.</p>
    <p>The forefront of Exoticteptilestore is our prestigious client bolster group. Be that as it may, the stays of our business are our extraordinary costs, wide choice, speed of conveyance, and prevalent administration. A demonstration of that is the way that we deliver 97% of requests same-day. We structured Exoticteptilestore with the aim of giving not just the best items at the most competitive costs, yet to wind up the #1 supplier of pet items, training, and data. Exoticteptilestore has a standout amongst the most dynamic online networks of pet proprietors on the Internet today.</p>
    <p>Inside our pet gathering, there is a wide scope of subjects talked about with new themes being included each day. A standout amongst the most energizing motivations to visit our gathering is on the grounds that we have utilized huge numbers of the business most-regarded pet creators to handle your inquiries and discussion about their subject matters.
    </p>
    <br>
    <br>
</div>
</body>
{% endblock %}

templates/ballpython.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
    <div class="left-column">
        <img src="{{url_for('static', filename='images/ballpython.jpg')}}"
            style="position: absolute; left: 7px; top:90px" />
    </div>

    <div class="right-column">

        <div class="product-description">
            <span>Snakes</span>
            <h1>Ball Python</h1>
            <p>A snake which is great for beginnner reptile keepers, Ball Pythons love being held and only need a simple set up to stay happy. Similarly to Corn Snakes, these docile snakes won't grow too big and come in many beautiful morphs. Like any smaller snake, they eat small rodents and need feeding every fortnight. It is recommended to buy a Vivarium to house them in, using substrate on the bottom giving them somewhere to cool down and hide, along with some logs to climb around on and a sheltered area to sleep in. heat lamp is necessary as they need a consistent temperature of around 28 to 32 degrees to survive.</p>
        </div>
        
        <div class="product-price">
            <span>£39.99</span>
            <button type = "button" class = "cart-btn" onclick="window.addCart()">Add to cart</button>
        </div>
</main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous">
    </script>
    <script src = "{{ url_for('static',filename='js/main.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}">

    <title></title>
</head>

<body>

    <img src="{{url_for('static', filename='images/logo.png')}}" class="center" height=13% width=27% />


    <nav class="navbar navbar-expand-lg" style="background-color: #49beb7;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav navbar-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.products')}}">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.care')}}">Animal Care</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.about')}}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.contact')}}">Contact Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.cart')}}">Your Cart</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>

<footer class="footer">
    <ul> Navigation
        <a class="nav-link" href="{{url_for('views.home')}}">Home</a>
        <a class="nav-link" href="{{url_for('views.products')}}">Products</a>
        <a class="nav-link" href="{{url_for('views.care')}}">Care</a>
        <a class="nav-link" href="{{url_for('views.about')}}">About</a>
        <a class="nav-link" href="{{url_for('views.contact')}}">Contact</a>
    </ul>
</footer>
</html>

templates/beardeddragon.html
{% extends 'base.html' %}

{% block content %}
<body>
<main class="container">
    <div class="left-column">
        <img src="{{url_for('static', filename='images/beardie.png')}}"
            style="position: absolute; left: 7px; top:90px" />
    </div>

    <div class="right-column">

        <div class="product-description">
            <span>Bearded Dragon</span>
            <h1>Bearded Dragon</h1>
            <p>Beardies are easy to care for, providing you have the right equipment. Their relatively small size, friendly nature and characterful behaviour make them and interesting and rewarding pet. They like to eat small insects and as with any reptiles require a vivarium and heat lamp with a hot temperature of around 37 degrees needed. It isn't recommended to house multiple together as they may end up fighting and causing eachother injury. Bearded dragons thrive in a low humidity environment with hard decorations to climb over and bask on. When selecting a bedding we try to ensure that the pieces are unlikely to stick to the dragon's food, and are not going to increase the enclosures humidity.</p>
        </div>
        
        <div class="product-price">
            <span>£79.99</span>
            <button type = "button" class = "cart-btn" onclick="window.addCart()">Add to cart</button>
        </div>
</main>
</body>
{% endblock %}

templates/care.html
{% extends 'base.html' %}

{% block content %}
<div class="about">
    <h3>Animal Care</h3>
    <img src="{{url_for('static', filename='images/handle-corn.jpg')}}" alt="image of store" height=10% width=20% />
    <h5>Corn Snake Handling</h5>
    <p>You will need to wait a little while after bringing your new pet home to let it settle in. This usually takes
        about 2 weeks, but you shouldn’t start handling until it’s eating regularly. Once your corn snake is ready for
        handling, take it slow at first — just like any relationship. Start with brief handling sessions (no longer than
        5 minutes), and don’t return the snake until it is calm. This teaches your pet how to behave during handling by
        using rudimentary positive reinforcement. Once this has been accomplished, you can work up to 10 minutes, and
        then gradually longer from there. Corn snake handling should occur least 1-2x weekly, but no more than once
        daily. Snakes do not require social interaction for their mental health, but handling helps the snake stay tame
        and can be a good opportunity for exercise as well. Use your hand(s) to approach your snake from the side —
        approaching from above may trigger a defensive instinct, as predators often attack from above in the wild. As
        you pick it up, hold as much of its body as you can, and avoid grabbing the tail or restraining the head.</p>
    </div>
    <br>
    <br>
    <br>
    <div class="care2">
        <h5>Chameleon Care</h5>
        <img src="{{url_for('static', filename='images/cham-care.png')}}" alt="image of store" height=10% width=20% />
    </div>
    <div class = "about">
    <p>The natural habits of chameleons make them tricky to care for. Chameleons are arboreal, meaning they live
        exclusively in trees. They need cages with ample foliage for climbing and privacy, and the enclosure must be
        quite large. For the larger chameleons a cage measuring 3 feet by 3 feet by 4 feet tall should be provided, but
        the more space the better. Ample ventilation is required, and a cage screened on three sides is best with poly
        mesh or vinyl coated wire preferred to prevent toe injuries. Branches of various diameters need to be provided
        for climbing and the bulk of the cage space should be filled with these branches or live foliage. Ensure that
        the plants are not toxic, as the chameleon may eat the foliage. Substrate made up of small particles (such as
        gravel, sand, bark, or moss) should be avoided to prevent the chameleon from accidentally eating it while
        catching prey. Several basking areas of various temperatures must also be provided in a chameleon's enclosure.
        Some chameleons are happier at higher temperatures, others at lower temperatures. Be sure to research the
        specifics for your breed. Chameleons get their water from droplets on leaves so as a rule, they will not take
        water from a dish. Adequate water intake must be provided either through a drip system or by misting the
        enclosure at least twice daily. Drip systems can be purchased or fashioned from a water container with a pinhole
        placed on top of the cage, or even by placing ice cubes on top of the cage to melt slowly and drip into the
        cage. If a drip system is used, keep the watering location consistent so the chameleon knows where to find
        water. Misting will also help keep the humidity levels up. With a drip system, excess water should be collected
        and removed to prevent the humidity from getting too high.</p>
    </div>
{% endblock %}

templates/cart.html
{% extends 'base.html' %}

{% block content %}
<h3> Your Cart</h3>

<div class = "cart-contain">
    <div class="header">
        <h3 class="heading">Items</h3>
        <h5 class="action">Remove all</h5>
    </div>
    <div class="Cart-Items">
        <div class="image-box">
            <img src="{{url_for('static', filename='images/crestedgecko.jpg')}}"/>
        </div>
        <div class="details">
            <h5 class="title">Crested Gecko</h5>
        </div>
        <div class="counter">
            <div class="btn">+</div>
            <div class="count">2</div>
            <div class="btn">-</div>
        </div>
        <div class="prices">
            <div class="amount">£29.99</div>
            <div class="remove"><u>Remove</u></div>
            </div>
        </div>
        <div class="Cart-Items">
            <div class="image-box">
                <img src="{{url_for('static', filename='images/gecko_about.jpg')}}"/>
            </div>
            <div class="details">
                <h5 class="title">Leopard Gecko</h5>
            </div>
            <div class="counter">
                <div class="btn">+</div>
                <div class="count">1</div>
                <div class="btn">-</div>
            </div>
            <div class="prices">
                <div class="amount">£29.99</div>
                <div class="remove">
                    <u>Remove</u></div>
                </div>
            </div>
            <div class ="total"> Total: </div>
            <div class ="checkout-btn">
                <button>Checkout</button>
            </div>
            <br>
</div>
{% endblock %}

templates/chameleon.html
{% extends 'base.html' %}

{% block content %}
<body>
<main class="container">
    <div class="left-column">
        <img src="{{url_for('static', filename='images/chameleon.jpg')}}"
            style="position: absolute; left: 7px; top:90px" />
    </div>

    <div class="right-column">

        <div class="product-description">
            <span>Chameleons</span>
            <h1>Baby Chameleon</h1>
            <p>Chameleons are one of the most popular arboreal lizards to keep in the UK. They are very active, inquisitive and firm favourites with keepers that do not have a lot of time to handle their pet. The longest lived chameleons could live 5-10 years. Their diet mostly consists of invertebrates though some species will supplement their diet with very small mammals or vegetation. Chameleons In captivity are particularly fond of crickets and locust but they can tackle larger prey like mealworms or grubs as a treat. They are not recommended for beginner reptile keepers as they can be pretty high maintainence & need constant checking of temperature and humidity to survive.</p>
        </div>
        
        <div class="product-price">
            <span>£79.99</span>
            <button type = "button" class = "cart-btn" onclick="window.addCart()">Add to cart</button>
        </div>
</main>
</body>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<body>
<h3>Contact Us</h3>
<div class="container">
    <form onsubmit="return false">
        <label>First Name</label>
        <input type="text" placeholder="first name" id="firstName" />
        <label>Last Name</label>
        <input type="text" placeholder="last name" id="lastName" />
        <label>Email Address</label>
        <input type="text" placeholder="email" id="email" />
        <br>
        <label> Reason for contact</label>
        <select id="reason">
            <option disabled selected value> -- reason for enquiry -- </option>
            <option value="Refund">Refund</option>
            <option value="Enquiry">Enquiry</option>
            <option value="Complaint">Complaint</option>
        </select>
        <br>
        <textarea id="feedback" rows="4"></textarea>
        <br><br>
        <button type = "button" onclick= "window.submit();" >Submit</button>
    </form>
</div>
</body>
{% endblock %}

templates/crestedgecko.html
{% extends 'base.html' %}

{% block content %}
<body>
<main class="container">
    <div class="left-column">
        <img src="{{url_for('static', filename='images/crestedgecko.jpg')}}"
            style="position: absolute; left: 7px; top:90px" />
    </div>

    <div class="right-column">

        <div class="product-description">
            <span>Crested Geckos</span>
            <h1>Green Crested Gecko</h1>
            <p>These fun little guys are a great pet for anyone, as they are friendly and love to be handled, whilst having relatively cheap setup and only eat small insects. Like most reptiles, a small vivarium is needed with a heat lamp and somewhere for them to hide. They like temperatures of around 31 degrees to bask in. It is not recommended to house more than one Gecko together, so make sure if purchasing multiple to have room for multiple vivariums to house them. </p>
        </div>
        
        <div class="product-price">
            <span>£29.99</span>
            <<button type = "button" class = "cart-btn" onclick="window.addCart()">Add to cart</button>
        </div>
</main>
</body>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h3>Welcome to Exotictreptilestore!</h3>
<br>
<p>Here at Exotictreptilestore, we provide you with healthy animals, packaged safe and securely and offer amazing
    aftercare to help whenever you may need!</p>

<h4>Featured Products</h4>

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{{url_for('static', filename='images/ballpython.jpg')}}"  alt="First slide">
              <div class="carousel-caption d-none d-md-block">
                <h5>Ball Python</h5>
                <a href = "{{url_for('views.ballpython')}}">See Now</a>
              </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{{url_for('static', filename='images/crestedgecko.jpg')}}" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
              <h5>Crested Gecko</h5>
              <a href = "{{url_for('views.crestedgecko')}}">See Now</a>
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{{url_for('static', filename='images/chameleon.jpg')}}" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
              <h5>Chameleon</h5>
              <a href = "{{url_for('views.chameleon')}}">See Now</a>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="sr-only">Next</span>
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
      </div>

      <div class="product-flex-container">
        <div>
            <img src="{{url_for('static', filename='images/baby_corn.jpg')}}" style ="height: 100%; width: 100%;"/>
            <br>
            <a href="{{url_for('views.redcorn')}}">Red Corn Snake - £39.99</a>
            <br>
            <button>Buy Now</button>
        </div>
        <div>
            <img src="{{url_for('static', filename='images/gecko_about.jpg')}}" style ="height: 100%; width: 100%"/>
            <br>
            <a href="{{url_for('views.yellowgecko')}}">Leopard Gecko - £29.99</a>
            <br>
            <button>Buy Now</button>
        </div>
        <div>
            <img src="{{url_for('static', filename='images/beardie.png')}}" style ="height: 100%; width: 100%"/>
            <br>
            <a href="{{url_for('views.beardeddragon')}}">Bearded Dragon - £59.99</a>
            <br>
            <button>Buy Now</button>
        </div>  
    </div>

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}

templates/products.html
{% extends 'base.html' %}

{% block content %}

<body>
<h3>Products</h3>

<div class="product-flex-container">
    <div>
        <img src="{{url_for('static', filename='images/baby_corn.jpg')}}" style ="height: 100%; width: 100%;"/>
        <br>
        <a href="{{url_for('views.redcorn')}}">Red Corn Snake - £39.99</a>
        <br>
        <button type = "button" onclick="window.addCart()">Buy Now</button>
    </div>
    <div>
        <img src="{{url_for('static', filename='images/gecko_about.jpg')}}" style ="height: 100%; width: 100%"/>
        <br>
        <a href="{{url_for('views.yellowgecko')}}">Leopard Gecko - £29.99</a>
        <br>
        <button type = "button" onclick="window.addCart()">Buy Now</button>
    </div>
    <div>
        <img src="{{url_for('static', filename='images/beardie.png')}}" style ="height: 100%; width: 100%"/>
        <br>
        <a href="{{url_for('views.beardeddragon')}}">Bearded Dragon - £59.99</a>
        <br>
        <button type = "button" onclick="window.addCart()">Buy Now</button>
    </div>  
</div>

<div class="product-flex-container">
    <div>
        <img src="{{url_for('static', filename='images/ballpython.jpg')}}"/>
        <br>
        <a href="{{url_for('views.ballpython')}}">Baby Ball Python - £39.99</a>
        <br>
        <button type = "button" onclick="window.addCart()">Buy Now</button>
    </div>
    <div>
        <img src="{{url_for('static', filename='images/crestedgecko.jpg')}}"/>
        <br>
        <a href="{{url_for('views.crestedgecko')}}">Crested Gecko - £29.99</a>
        <br>
        <button type = "button" onclick="window.addCart()">Buy Now</button>
    </div>
    <div>
        <img src="{{url_for('static', filename='images/chameleon.jpg')}}"/>
        <br>
        <a href="{{url_for('views.chameleon')}}">Chameleon - £79.99</a>
        <br>
        <button type = "button" onclick="window.addCart()">Buy Now</button>
    </div>  
</div>
</body>
{% endblock %}

templates/redcorn.html
{% extends 'base.html' %}

{% block content %}
<body>
<main class="container">
    <div class="left-column">
        <img src="{{url_for('static', filename='images/baby_corn.jpg')}}" style="position: absolute; left: 7px; top:90px"/>
    </div>

    <div class="right-column">

        <div class="product-description">
            <span>Snakes</span>
            <h1>Baby Red Corn Snake</h1>
            <p> Corn Snakes are perfect first snake pets for any age. Beautifully patterned, this red corn snake will grow to a maximum of 6ft. They eat small rodents and are a low maintainence pet, who also love to be handled by humans. It is recommended to buy a Vivarium to house them in, using substrate on the bottom giving them somewhere to cool down and hide, along with some logs to climb around on and a sheltered area to sleep in. heat lamp is necessary as they need a consistent temperature of around 28 to 32 degrees to survive. </p>
        </div>

        <div class="product-price">
            <span>£39.99</span>
            <button type = "button" class = "cart-btn" onclick="window.addCart()">Add to cart</button>
        </div>
    </div>
</main>
</body>
    {% endblock %}

templates/yellowgecko.html
{% extends 'base.html' %}

{% block content %}
<body>
<main class="container">
    <div class="left-column">
        <img src="{{url_for('static', filename='images/gecko_about.jpg')}}" style="position: absolute; left: 7px; top:90px"/>
    </div>

    <div class="right-column">

        <div class="product-description">
            <span>Leopard Gecko</span>
            <h1>Yellow Leopard Gecko</h1>
            <p>These fun little guys are a great pet for anyone, as they are friendly and love to be handled, whilst having relatively cheap setup and only eat small insects. Like most reptiles, a small vivarium is needed with a heat lamp and somewhere for them to hide. They like temperatures of around 31 degrees to bask in. It is not recommended to house more than one Gecko together, so make sure if purchasing multiple to have room for multiple vivariums to house </p>
        </div>

        <div class="product-price">
            <span>£29.99</span>
            <button type = "button" class = "cart-btn" onclick="window.addCart()">Add to cart</button>
        </div>
    </div>
</main>
</body>
    {% endblock %}